from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


# =========================================================
# REPORT SECTION
# =========================================================

class ReportSection(BaseModel):

    """
    Represents a single report section.
    """

    title: str = Field(
        ...,
        description="Section title",
    )

    content: str = Field(
        ...,
        description="Section content",
    )


# =========================================================
# REPORT METADATA
# =========================================================

class ReportMetadata(BaseModel):
    """
    Metadata associated with the report.
    """

    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
    )

    generated_by: str = Field(
        default="Coach Genie AI",
    )

    # ✅ Make report_type optional
    report_type: Optional[str] = Field(
        default=None,
        description="Type of report",
    )

    user_id: Optional[str] = Field(
        default=None,
    )

    session_id: Optional[str] = Field(
        default=None,
    )

    trace_id: Optional[str] = Field(
        default=None,
    )



# =========================================================
# MAIN REPORT SCHEMA
# =========================================================

class ReportSchema(BaseModel):

    """
    Main report schema.
    """

    title: str = Field(
        ...,
        description="Main report title",
    )

    summary: Optional[str] = Field(
        default=None,
    )

    metadata: ReportMetadata

    sections: List[ReportSection] = Field(
        default_factory=list,
    )

    footer: Optional[str] = Field(
        default="Generated by Coach Genie AI",
    )
    
# ===========================================================
# V2 SCHEMA DESIGN (FUTURE PROOFING)
# ===========================================================

# from datetime import datetime
# from typing import List, Optional, Dict, Any, Union
# from pydantic import BaseModel, Field


# # =========================================================
# # ENUM-LIKE TYPES (FUTURE READY)
# # =========================================================

# SectionType = str  # can evolve into Enum later
# ContentType = str   # paragraph | bullets | table | metrics


# # =========================================================
# # METRICS BLOCK (for analytics style reports)
# # =========================================================

# class MetricItem(BaseModel):
#     label: str
#     value: Union[str, int, float]
#     trend: Optional[str] = Field(default=None)  # up / down / stable
#     color: Optional[str] = Field(default=None)


# # =========================================================
# # TABLE BLOCK (for structured data)
# # =========================================================

# class TableBlock(BaseModel):
#     headers: List[str]
#     rows: List[List[Any]]


# # =========================================================
# # SECTION CONTENT (UNIFIED FLEXIBLE MODEL)
# # =========================================================

# class SectionContent(BaseModel):

#     type: ContentType = Field(
#         default="paragraph",
#         description="paragraph | bullets | metrics | table",
#     )

#     text: Optional[str] = None

#     bullets: Optional[List[str]] = None

#     metrics: Optional[List[MetricItem]] = None

#     table: Optional[TableBlock] = None


# # =========================================================
# # REPORT SECTION (UPGRADED)
# # =========================================================

# class ReportSection(BaseModel):

#     title: str = Field(..., description="Section title")

#     subtitle: Optional[str] = None

#     section_type: SectionType = Field(
#         default="standard",
#         description="standard | analysis | recommendation | summary | warning",
#     )

#     content: SectionContent

#     priority: Optional[int] = Field(
#         default=1,
#         description="Rendering priority (1 = high, 5 = low)",
#     )

#     tags: Optional[List[str]] = Field(
#         default_factory=list,
#         description="AI-generated tags for filtering/searching",
#     )


# # =========================================================
# # REPORT METADATA (PRODUCTION-GRADE)
# # =========================================================

# class ReportMetadata(BaseModel):

#     generated_at: datetime = Field(default_factory=datetime.utcnow)

#     generated_by: str = Field(default="Coach Genie AI")

#     report_type: Optional[str] = None

#     user_id: Optional[str] = None

#     session_id: Optional[str] = None

#     trace_id: Optional[str] = None

#     version: str = Field(default="v2")

#     model: Optional[str] = Field(default=None)  # e.g., llama3, gpt-4

#     source: Optional[str] = Field(default=None)  # groq / openai / local

#     latency_ms: Optional[int] = None

#     confidence_score: Optional[float] = None


# # =========================================================
# # MAIN REPORT SCHEMA (V2 ENGINE)
# # =========================================================

# class ReportSchema(BaseModel):

#     title: str = Field(..., description="Main report title")

#     summary: Optional[str] = Field(
#         default=None,
#         description="Executive summary of report",
#     )

#     metadata: ReportMetadata

#     sections: List[ReportSection] = Field(
#         default_factory=list,
#     )

#     footer: Optional[str] = Field(
#         default="Generated by Coach Genie AI",
#     )

#     style_theme: Optional[str] = Field(
#         default="default",
#         description="default | executive | academic | minimal",
#     )

#     language: str = Field(
#         default="en",
#     )

#     is_ai_generated: bool = Field(
#         default=True,
#     )