from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


# =========================================================
# REPORT SECTION
# =========================================================

class ReportSection(BaseModel):

    """
    Represents a single report section.
    """

    title: str = Field(
        ...,
        description="Section title",
    )

    content: str = Field(
        ...,
        description="Section content",
    )


# =========================================================
# REPORT METADATA
# =========================================================

class ReportMetadata(BaseModel):

    """
    Metadata associated with the report.
    """

    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
    )

    generated_by: str = Field(
        default="Coach Genie AI",
    )

    report_type: str = Field(
        ...,
        description="Type of report",
    )

    user_id: Optional[str] = Field(
        default=None,
    )

    session_id: Optional[str] = Field(
        default=None,
    )

    trace_id: Optional[str] = Field(
        default=None,
    )


# =========================================================
# MAIN REPORT SCHEMA
# =========================================================

class ReportSchema(BaseModel):

    """
    Main report schema.
    """

    title: str = Field(
        ...,
        description="Main report title",
    )

    summary: Optional[str] = Field(
        default=None,
    )

    metadata: ReportMetadata

    sections: List[ReportSection] = Field(
        default_factory=list,
    )

    footer: Optional[str] = Field(
        default="Generated by Coach Genie AI",
    )